# fly.toml app configuration file generated for grpc-climate on 2023-06-11T16:41:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "grpc-climate"
primary_region = "cdg"

[[services]]
  protocol = "tcp"
  internal_port = 50051

  [[services.ports]]
    port = 443
    handlers = ["tls"]
    [services.ports.tls_options]
      alpn = ["h2"]
