# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tmax.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntmax.proto\x12\x06netcdf\"M\n\x0c\x44\x61teLocation\x12\x18\n\x10\x64\x61ys_since_start\x18\x01 \x01(\r\x12\x10\n\x08latitude\x18\x02 \x01(\x02\x12\x11\n\tlongitude\x18\x03 \x01(\x02\"\x1c\n\x0bTemperature\x12\r\n\x05value\x18\x01 \x01(\x02\x32?\n\x04Tmax\x12\x37\n\x08GetValue\x12\x14.netcdf.DateLocation\x1a\x13.netcdf.Temperature\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tmax_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATELOCATION._serialized_start=22
  _DATELOCATION._serialized_end=99
  _TEMPERATURE._serialized_start=101
  _TEMPERATURE._serialized_end=129
  _TMAX._serialized_start=131
  _TMAX._serialized_end=194
# @@protoc_insertion_point(module_scope)
