# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tmax.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntmax.proto\x12\x07\x63limate\"M\n\x0c\x44\x61teLocation\x12\x18\n\x10\x64\x61ys_since_start\x18\x01 \x01(\r\x12\x10\n\x08latitude\x18\x02 \x01(\x02\x12\x11\n\tlongitude\x18\x03 \x01(\x02\"/\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\"\x1c\n\x0bTemperature\x12\r\n\x05value\x18\x01 \x01(\x02\x32\x81\x01\n\x04Tmax\x12\x39\n\x08GetValue\x12\x15.climate.DateLocation\x1a\x14.climate.Temperature\"\x00\x12>\n\x0fGetTemperatures\x12\x11.climate.Location\x1a\x14.climate.Temperature\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tmax_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATELOCATION']._serialized_start=23
  _globals['_DATELOCATION']._serialized_end=100
  _globals['_LOCATION']._serialized_start=102
  _globals['_LOCATION']._serialized_end=149
  _globals['_TEMPERATURE']._serialized_start=151
  _globals['_TEMPERATURE']._serialized_end=179
  _globals['_TMAX']._serialized_start=182
  _globals['_TMAX']._serialized_end=311
# @@protoc_insertion_point(module_scope)
