# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tmax_pb2 as tmax__pb2


class TmaxStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetValue = channel.unary_unary(
                '/climate.Tmax/GetValue',
                request_serializer=tmax__pb2.DateLocation.SerializeToString,
                response_deserializer=tmax__pb2.Temperature.FromString,
                )
        self.GetTemperatures = channel.unary_stream(
                '/climate.Tmax/GetTemperatures',
                request_serializer=tmax__pb2.Location.SerializeToString,
                response_deserializer=tmax__pb2.Temperature.FromString,
                )


class TmaxServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTemperatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TmaxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValue,
                    request_deserializer=tmax__pb2.DateLocation.FromString,
                    response_serializer=tmax__pb2.Temperature.SerializeToString,
            ),
            'GetTemperatures': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTemperatures,
                    request_deserializer=tmax__pb2.Location.FromString,
                    response_serializer=tmax__pb2.Temperature.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'climate.Tmax', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tmax(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/climate.Tmax/GetValue',
            tmax__pb2.DateLocation.SerializeToString,
            tmax__pb2.Temperature.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTemperatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/climate.Tmax/GetTemperatures',
            tmax__pb2.Location.SerializeToString,
            tmax__pb2.Temperature.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
